const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let products=[],categories=[],config={},cart=JSON.parse(localStorage.getItem('mmc-cart')||'[]');
async function api(u,o){const r=await fetch(u,{headers:{'Content-Type':'application/json',...(o?.headers||{})},...o});const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro');return d}
function money(n){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n)} function save(){localStorage.setItem('mmc-cart',JSON.stringify(cart));renderCartCount()}
function renderCartCount(){const n=cart.reduce((a,x)=>a+x.qty,0);$('#cartCount').textContent=n}
function card(p){const img=p.images?.find(x=>x.is_main)?.url||p.images?.[0]?.url||'/assets/product-placeholder.svg';const price=p.promo_price||p.price;return `<a class="card" href="/produto/${p.slug}" style="text-decoration:none;color:inherit"><div class="photo"><img src="${img}">${p.on_sale?'<span class="badge">Oferta</span>':''}</div><div class="info"><h3>${p.name}</h3><div class="price">${p.promo_price?`<span class="old">${money(p.price)}</span>`:''}${money(price)}</div></div></a>`}
async function init(){config=await api('/api/config');document.documentElement.style.setProperty('--ink',config.primaryColor||'#2b2023');$('#brand').textContent=config.storeName;$('#footerBrand').textContent=config.storeName;$('#slogan').textContent=config.slogan;$('#wa').href=`https://wa.me/${config.whatsapp}`;categories=await api('/api/categories');$('#cats').innerHTML=categories.slice(0,6).map(c=>`<a class="cat" href="/categoria/${c.slug}">${c.name}</a>`).join('');products=await api('/api/products?sort=new');$('#featured').innerHTML=products.slice(0,8).map(card).join('');renderCartCount()}
function openCart(){const d=$('#drawer');d.classList.add('open');renderCart()}function closeCart(){$('#drawer').classList.remove('open')}
function renderCart(){const el=$('#cartItems');if(!cart.length){el.innerHTML='<div class="empty">Seu carrinho está vazio.</div>';$('#cartTotal').textContent=money(0);return}let total=0;el.innerHTML=cart.map((x,i)=>{total+=x.price*x.qty;return `<div style="display:flex;gap:12px;margin:15px 0;border-bottom:1px solid var(--line);padding-bottom:15px"><img src="${x.image}" style="width:70px;height:88px;object-fit:cover"><div style="flex:1"><b>${x.name}</b><div style="font-size:12px;color:#777">${x.size} · ${x.color}</div><div>${money(x.price)} × ${x.qty}</div><button onclick="removeCart(${i})" style="border:0;background:none;padding:4px 0">Remover</button></div></div>`}).join('');$('#cartTotal').textContent=money(total)}
function removeCart(i){cart.splice(i,1);save();renderCart()}
window.removeCart=removeCart;window.openCart=openCart;window.closeCart=closeCart;
async function pageProduct(){const slug=location.pathname.split('/').pop();const p=await api('/api/products/'+slug);let size=p.variants[0]?.size||'',color=p.variants[0]?.color||'';const img=p.images?.find(x=>x.is_main)?.url||p.images?.[0]?.url||'/assets/product-placeholder.svg';$('#app').innerHTML=`<section><div class="container product"><div class="gallery"><div class="thumbs">${p.images.map(i=>`<img src="${i.url}" onclick="document.querySelector('#mainpic').src='${i.url}'">`).join('')}</div><img id="mainpic" class="mainpic" src="${img}"></div><div><div class="eyebrow">${p.category||'Coleção'}</div><h1 class="title">${p.name}</h1><p>${p.description||''}</p><h2>${money(p.promo_price||p.price)}</h2><p><b>Tamanho</b></p><div class="choice" id="sizes">${[...new Set(p.variants.map(v=>v.size))].map(s=>`<button onclick="pickSize('${s}')">${s}</button>`).join('')}</div><p><b>Cor</b></p><div class="choice" id="colors">${[...new Set(p.variants.map(v=>v.color))].map(c=>`<button onclick="pickColor('${c}')">${c}</button>`).join('')}</div><label>Quantidade <input class="input" id="qty" type="number" min="1" value="1" style="width:90px;flex:none"></label><br><br><button class="btn" id="add">Adicionar ao carrinho</button><div style="margin-top:30px"><b>Detalhes</b><p>${p.details||'—'}</p><p><b>Composição:</b> ${p.composition||'—'}</p><p><b>Cuidados:</b> ${p.washing||'—'}</p><p><b>Medidas:</b> ${p.measurements||'—'}</p></div></div></div></section>`;window.pickSize=s=>{size=s;$$('#sizes button').forEach(b=>b.classList.toggle('active',b.textContent===s))};window.pickColor=c=>{color=c;$$('#colors button').forEach(b=>b.classList.toggle('active',b.textContent===c))};$('#add').onclick=()=>{const v=p.variants.find(v=>v.size===size&&v.color===color);if(!v||v.stock<1)return toast('Selecione uma combinação disponível');const qty=Math.max(1,Number($('#qty').value));if(qty>v.stock)return toast('Quantidade maior que o estoque');cart.push({productId:p.id,variantId:v.id,name:p.name,size,color,qty,price:p.promo_price||p.price,image:img});save();toast('Produto adicionado ao carrinho');setTimeout(openCart,350)}}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}window.toast=toast;
function home(){return `<div class="hero" style="${config.heroBanner?`background-image:url('${config.heroBanner}');background-size:cover`:''}"><div><div class="eyebrow">MARIANE MOREIRA CONCEPT</div><h1>${config.heroTitle||'Elegância que fala por você.'}</h1><p id="slogan">${config.heroText||'Moda feminina com identidade.'}</p><a class="btn" href="#novidades">Descobrir novidades</a></div></div><section id="novidades"><div class="container"><div class="section-head"><div><div class="eyebrow">Curadoria da semana</div><h2 class="title">Novidades</h2></div><a href="/loja">Ver tudo →</a></div><div class="grid" id="featured"></div></div></section><section style="background:var(--cream)"><div class="container"><div class="eyebrow">Explore</div><h2 class="title">Categorias</h2><div class="categories" id="cats"></div></div></section>`}
function shop(){return `<section><div class="container"><div class="eyebrow">Coleção completa</div><h1 class="title">Loja</h1><div class="toolbar"><input id="q" class="input" placeholder="Buscar produtos..."><select id="sort" class="select"><option value="new">Novidades</option><option value="price_asc">Menor preço</option><option value="price_desc">Maior preço</option><option value="bestseller">Mais vendidos</option></select></div><div class="grid" id="shopGrid"></div></div></section>`}
async function render(){if(location.pathname.startsWith('/produto/')){$('#app').innerHTML='';await pageProduct();return}$('#app').innerHTML=(location.pathname==='/loja'||location.pathname.startsWith('/categoria/'))?shop():home();if(location.pathname==='/loja'||location.pathname.startsWith('/categoria/')){const load=async()=>{$('#shopGrid').innerHTML=(await api('/api/products?q='+encodeURIComponent($('#q').value)+'&sort='+$('#sort').value+(location.pathname.startsWith('/categoria/')?'&category='+encodeURIComponent(location.pathname.split('/').pop()):''))).map(card).join('')};$('#q').oninput=load;$('#sort').onchange=load;load()}else await init()}
render();
